#!/bin/sh
rm -Rf repo
mkdir repo
ln -s ../../../repo/haxe/tests repo/tests
svn co http://hxcpp.googlecode.com/svn/trunk/ repo/hxcpp
git clone git://github.com/waneck/hxjava.git repo/hxjava
git clone git://github.com/waneck/hxcs.git repo/hxcs
haxelib dev hxcpp $PWD/repo/hxcpp
haxelib dev hxjava $PWD/repo/hxjava
haxelib dev hxcs $PWD/repo/hxcs

cd repo
#apt-get 
sudo apt-get install openjdk-7-jre openjdk-7-jdk xvfb g++ mono-mcs php5-cli

#mxmlc
mkdir mxmlc; cd mxmlc
wget http://download.macromedia.com/pub/flex/sdk/flex_sdk_4.1.zip
unzip flex_sdk_4.1.zip
rm flex_sdk_4.1.zip
wget http://airdownload.adobe.com/air/lin/download/2.6/AdobeAIRSDK.tbz2
mkdir temp
tar -jxvf AdobeAIRSDK.tbz2 -C temp
cp temp/bin/adl bin/
cp -rf temp/runtimes/air/linux runtimes/air/linux
cd ..



# mkdir redtamarin; cd redtamarin
# wget https://redtamarin.googlecode.com/files/redtamarin_0.3.2.1170_NIX.zip
# unzip redtamarin_0.3.2.1170_NIX.zip
# chmod 777 redshell
# chmod 777 redshell_d
# wget https://maashaack.googlecode.com/files/avmglue_0.1.0.2305.zip
# unzip avmglue_0.1.0.2305.zip

